name: products
label: 物料
icon: contact
enable_api: true
fields:
  name:
    type: text
    label: 物料名称
    required: true
    searchable: true
    index: true
  code:
    type: text
    label: 物料编码
  description:
    type: textarea
    label: 描述
    is_wide: true
  product_category:
    label: 物料分类
    type: lookup
    reference_to: product_category
    sortable: true
    filterable: true
    searchable: true
list_views:
  all:
    label: 所有分类
    columns:
      - name
      - created

permission_set:
  user:
    allowCreate: false
    allowDelete: false
    allowEdit: false
    allowRead: true
    modifyAllRecords: false
    viewAllRecords: true 
  admin:
    allowCreate: true
    allowDelete: true
    allowEdit: true
    allowRead: true
    modifyAllRecords: true
    viewAllRecords: true
