name: products
label: 物料
icon: fulfillment_order
enable_api: true
enable_files: true
fields:
  name:
    type: text
    label: 物料名称
    required: true
    searchable: true
    index: true
  code:
    type: text
    label: 物料编码
  price:
    type: number
    label: 单价
    scale: 2
  unit:
    type: text
    label: 单位
  description:
    type: textarea
    label: 描述
    is_wide: true
  product_category:
    label: 物料分类
    type: master_detail
    reference_to: product_category
    sortable: true
    filterable: true
    searchable: true
list_views:
  all:
    label: 所有物料
    columns:
      - name
      - code
      - price
      - unit
      - product_category

permission_set:
  user:
    allowCreate: true
    allowDelete: true
    allowEdit: true
    allowRead: true
    modifyAllRecords: false
    viewAllRecords: true 
  admin:
    allowCreate: true
    allowDelete: true
    allowEdit: true
    allowRead: true
    modifyAllRecords: true
    viewAllRecords: true
  supplier:
    allowCreate: false
    allowDelete: false
    allowEdit: false
    allowRead: true
    modifyAllRecords: false
    viewAllRecords: true
    unreadable_fields: ['price','description','product_category'] 
