name: product_category
label: 物料分类
icon: contact
enable_api: true
fields:
  name:
    type: text
    label: 分类名称
    required: true
    searchable: true
    index: true
  # 此字段需要自动计算
  full_name:
    type: text
    label: 完整名称
    omit: true
    readonly: true
  parent_id:
    label: 上级分类
    type: lookup
    reference_to: product_category
    sortable: true
    filterable: true
    searchable: true
  # 此字段需要自动计算
  product_count:
    type: number
    label: 产品数量
    inlineHelpText: The number of products under this category (Does not consider the children categories)
    omit: true
    readonly: true

list_views:
  all:
    label: 所有分类
    columns:
      - name
      - parent_id
      - created

permission_set:
  user:
    allowCreate: false
    allowDelete: false
    allowEdit: false
    allowRead: true
    modifyAllRecords: false
    viewAllRecords: true 
  admin:
    allowCreate: true
    allowDelete: true
    allowEdit: true
    allowRead: true
    modifyAllRecords: true
    viewAllRecords: true
